### ISSUE TITLE
format file PDF don't upload

### ISSUE THREAD

**Issue by darkmic83** [ShekharTarare/File-Uploader-Using-Classic-ASP#1]
Hi, very interesting this uploader.

I have tried on my local machine, I have a problem with extension file PDF.

How solve this problem?

Thanks, very much

**Comment by ShekharK2s** [comment]
Hi @darkmic83 , Did you follow the steps mentioned [here](https://shekhartarare.com/Archive/2023/6/building_a_classic_asp_file_uploader) It's working as expected when tried the pdf file.

**Comment by ShekharTarare** [comment]
Hi @darkmic83, Did you follow the steps mentioned [here](https://shekhartarare.com/Archive/2023/6/building_a_classic_asp_file_uploader). I am able to upload pdf files without any issues. Any errors?

**Comment by darkmic83** [comment]
An error occurred on the server when processing the URL. Please contact the system administrator.
If you are the system administrator please click [here](https://go.microsoft.com/fwlink/?LinkID=82731) to find out more about this error.

**Comment by ShekharTarare** [comment]
With the error, it seems like the issue with IIS server. Follow the steps [here](https://shekhartarare.com/Archive/2023/6/a_step_by_step_guide_to_setting_up_iis_in_windows) to setup the IIS server. Then try again. The steps needs to be followed to make the uploader working.
